name: Excavator ScoopInstaller/Scoop-GithubActions@main
on:
  schedule:
    - cron: "10 */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavator
        uses: ScoopInstaller/Scoop-GithubActions@main
        env:
          GITH_EMAIL: zxj@outlook.sg
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_UPDATED: "1"
