on:
  schedule:
    - cron: "0 * * * *"
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: shovel-org/GithubActions@main
        env:
          GITH_EMAIL: zxj@outlook.sg
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_UPDATED: "1"
